spring.datasource.url=jdbc:postgresql://db:5432/musicmood_db
spring.datasource.username=musicmood_user
spring.datasource.password=musicmood_pass
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
 
server.port=8080
 
spring.application.name=musicmood-backend